### ISSUE TITLE
Automate saving/restoring the session

### ISSUE THREAD

**Issue by nicksp** [danielcopper/wezterm-session-manager#11]
First off, I've followed the setup steps and things work as expected through key bindings. I want to take it a step further and automate saving the session when closing the terminal and restoring it when it opens up. I tried some events Wezterm provides but couldn't make things work. I tried calling `session_manager.restore_state(window)`, emitting `restore_session` event and simulating key press from inside `gui-startup`, `gui-attached`, and `mux-startup` events to restore the state but none of the variants worked. For the session save, there doesn't seem to be an appropriate event so it;s something that can still be done manually.

Did someone manage to make it work this way?

**Comment by danieluhl** [comment]
See #18 for loading on startup. I haven't been able to get automated save working.

**Comment by nicksp** [comment]
Thanks @danieluhl Session restore works on terminal startup 👏

**Comment by ylluminate** [comment]
New to WezTerm here, could you share an example of the full context of your config @nicksp to show how to automate session restore? So far I've been shooting blanks for some reason and I think seeing a fully contextualized config might resolve this easily (which I'm baffled as to why this isn't on the readme as of yet).
